---
- name: Add signing key
  ansible.builtin.rpm_key:
    key: "https://download.docker.com/linux/centos/gpg"
    state: present
  become: true
- name: Add repository into repo.d list
  ansible.builtin.yum_repository:
    name: docker
    description: docker repository
    baseurl: "https://download.docker.com/linux/centos/$releasever/$basearch/stable"
    enabled: true
    gpgcheck: true
    gpgkey: "https://download.docker.com/linux/centos/gpg"
  become: true
- name: create group
  ansible.builtin.group:
    name: docker
    state: present
  become: true
- name: Add docker users to docker group
  user:
    name: "{{ item }}"
    groups: docker
    append: true
  with_items: "{{ docker_users_group_for_redhat }}"
  become: true
- name: Install Required PKGS
  ansible.builtin.yum:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - python3-pip
    state: latest
    update_cache: true
  become: true
- name: Install Docker
  pip:
    name: docker
    executable: pip3
#  notify: Restart docker
  become: true
- name: Start Docker
  ansible.builtin.service:
    name: "docker"
    enabled: true
    state: started
  become: true
- name: Create Container
  docker_container:
    name: "{{ container_name }}"
    image: "{{ container_image }}"
    ports:
      - "8080:80"
  become: true