---
- name: Update apt-get repo and cache
  apt:
    update_cache: true
    force_apt_get: true
    cache_valid_time: 3600
  become: true
- name: Install required system packages
  apt:
    pkg:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
      - python3-pip
    state: latest
    update_cache: true
  become: true
- name: Add docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  become: true
- name: Add docker repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present
  become: true
- name: Install docker engine and docker compose
  apt:
    pkg: "{{ docker_engine_pkg_list }}"
    state: latest
    update_cache: true
  become: true
- name: Add docker users to docker group
  user:
    name: "{{ item }}"
    groups: docker
    append: true
  with_items: "{{ docker_users_group_for_ubuntu }}"
  become: true
- name: Install docker
  pip:
    name: docker
    executable: pip3
  notify: Restart docker
- name: Create Container
  docker_container:
    name: "{{ container_name }}"
    image: "{{ container_image }}"
    ports:
      - "8080:80"
  become: true